### ISSUE TITLE
[Under Investigation] Deployments Data Missing Upon Reinstall of Jira Plugin

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/JiraIntegration#100]
An investigation is underway to determine the cause of deployment data being removed in Jira Cloud. It appears to occur when a user uninstalls and reinstalls the Jira plugin; uninstalling the plugin removes all deployment-related data in Jira Cloud. This is NOT the behaviour that has been observed historically. Previously, users were able to successfully uninstall and reinstall this plugin without losing deployment data.

Since receiving reports of this behaviour, we have been able to reproduce it in our test environments.

**Comment by paraicoceallaigh** [comment]
The other current open ticket : https://octopus.zendesk.com/agent/tickets/86874 (private link)

**Comment by Clare-Octopus** [comment]
Another customer experiencing the 401 error [https://octopus.zendesk.com/agent/tickets/90045](https://octopus.zendesk.com/agent/tickets/90045 ) (internal ticket) 

Unable to publish data to Jira. Response code: BadRequest, Message: An error occurred while posting deployment info to Jira: Response status code does not indicate success: 401 (Unauthorized).

He has not uninstalled the app based on our new recommendations not to reinstall it as it deletes historical data. This is just to log how many 401 errors we are getting. At the moment the only fix we know for the 401 error is to reinstall.

Please do not do that, please disable the JIRA Integration within Octopus until we can get this fixed. Because re-installing the plugin deletes the data from previous days it seems pointless having the plugin enabled until a fix can be produced and you are able to use JIRA again.

**Comment by Clare-Octopus** [comment]
For all customers receiving the 401 error for their JIRA Status updates please refer to this [GitHub Issue](https://github.com/OctopusDeploy/Issues/issues/7596).
